UNEXISTED="$HOME/sidfhoiho"

DOTFILES="$HOME/dotfiles"
LIANHANGZ="$HOME/LianhangZ"
DOWNLOADS="$HOME/Downloads"

ICLOUD="$HOME/Library/Mobile Documents/com~apple~CloudDocs"
OBSIDIAN="$HOME/Library/Mobile Documents/iCloud~md~obsidian/Documents"
JUPYTER_KERNELS="$HOME/Library/Jupyter/kernels/"

PGHOME=$HOME/pgsql                  # ~/pgsql
export PGDATA=$PGHOME/data          # ~/pgsql/data
export PGHOST="localhost"
export PGPORT=5432
export LD_LIBRARY_PATH=$PGHOME/lib  # ~/pgsql/lib
export PATH=$PGHOME/bin:$PATH       # ~/pgsql/bin
