return {
  "stevearc/aerial.nvim",
  opts = {
    layout = {
      width = 0.2,
      default_direction = "right",
    },
    filter_kind = false,
    -- filter_kind = {
    --   "File",
    --   "Module",
    --   "Namespace",
    --   "Package",
    --   "Class",
    --   "Method",
    --   "Property",
    --   "Feild",
    --   "Constructor",
    --   "Enum",
    --   "Interface",
    --   "Function",
    --   "Variable",
    --   "Constant",
    --   -- "String",
    --   "Number",
    --   "Boolean",
    --   "Array",
    --   "Object",
    --   "Key",
    --   "Null",
    --   "Struct",
    -- },
    show_guides = true,
    icons = {
      File = "󰈙",
      Module = "󰆧",
      Namespace = "󰅪",
      Package = "󰏖",
      Class = "𝓒",
      Method = "󰆧",
      Property = "󰜢",
      Field = "󰜢",
      Constructor = "",
      Enum = "󰕘",
      Interface = "󰕘",
      Function = "󰊕",
      Variable = "󰀫",
      Constant = "󰏿",
      String = "󰀬",
      Number = "󰎠",
      Boolean = "◩",
      Array = "󰅪",
      Object = "󰅩",
      Key = "󰌋",
      Null = "󰟢",
    },
    guides = {
      mid_item = "├─",
      last_item = "└─",
      nested_top = "│ ",
      whitespace = "  ",
    },
  },
  keys = {
    {
      "<leader>o", -- "<leader>cs",
      "<cmd>AerialToggle!<CR>",
      desc = "󰙅 Outline",
    },
  },
  dependencies = {
    "nvim-treesitter/nvim-treesitter",
    "nvim-tree/nvim-web-devicons",
  },
}