on:
  push:
    paths:
      - 'macos/**/*.sh'
      - 'shared/**/*.sh'
      - '.github/workflows/test-macos.yml'

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: bootstrap
        run: |
          ln -s "$GITHUB_WORKSPACE" ~/dotfiles
          bash macos/bootstrap.sh

      - name: sync
        run: |
          bash macos/sync.sh